database_config:
  database_type: sqlite

  sqlite_database:
    db_file: C:\Users\maria\test.db
    timeout: 5000
    pool_size: 5

  mongodb_database:
    uri: mongodb://localhost:27017
    db_name: ruby_lab
